-- AlterEnum
ALTER TYPE "MatchStatus" ADD VALUE IF NOT EXISTS 'HALFTIME';
ALTER TYPE "MatchStatus" ADD VALUE IF NOT EXISTS 'DELAYED';

-- AlterTable
ALTER TABLE "Standing" ADD COLUMN IF NOT EXISTS "fair_play" INTEGER NOT NULL DEFAULT 0;
